fhir-bridge:
  fhir:
    narrative-generation: false
    url-mapping: /fhir/*
    validation:
      terminology:
        mode: remote
        remote:
          server-url: https://r4.ontoserver.csiro.au/fhir/
logging:
  level:
    ca.uhn.fhir: info
    org.ehrbase.fhirbridge: info
    org.hl7.fhir: info
server:
  servlet:
    context-path: /fhir-bridge
  port: 8888

ehrbase:
  address: localhost
  port: 8080
  path: /ehrbase/rest/openehr/v1/